# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tokenFieldExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'AFNetworking', '0.9.1'
pod 'TokenField', '~> 0.1.2'
  # Pods for tokenFieldExample

end
